# Dockerfile.api
FROM python:3.10-slim

# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier les fichiers dans le conteneur
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY ./app ./app
COPY app/ .

# Exposer le port 8000 pour FastAPI
EXPOSE 8000

ENV PYTHONPATH=/app
# Commande pour lancer l’API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
